mklink %HOMEPATH%"\.vimrc" %HOMEPATH%"\dotfiles\.vimrc"
mklink %HOMEPATH%"\.gvimrc" %HOMEPATH%"\dotfiles\.gvimrc"
mklink %HOMEPATH%"\.dein.toml" %HOMEPATH%"\dotfiles\.dein.toml"
mklink %HOMEPATH%"\.gitconfig" %HOMEPATH%"\dotfiles\.gitconfig"
rem mklink %HOMEPATH%"\.gdbinit" %HOMEPATH%"\dotfiles\.gdbinit"
rem mklink %HOMEPATH%"\.screenrc" %HOMEPATH%"\dotfiles\.screenrc"
rem mklink %HOMEPATH%"\.tmux.conf" %HOMEPATH%"\dotfiles\.tmux.conf"
mklink %HOMEPATH%"\.minttyrc" %HOMEPATH%"\dotfiles\.minttyrc"
mklink %HOMEPATH%"\.bashrc.additional" %HOMEPATH%"\dotfiles\.bashrc.additional"
rem mklink %HOMEPATH%"\.git_prompt.sh" %HOMEPATH%"\dotfiles\.git_prompt.sh"
mklink %HOMEPATH%"\git_clean.sh" %HOMEPATH%"\dotfiles\git_clean.sh"
mklink /d %HOMEPATH%"\vimfiles" %HOMEPATH%"\dotfiles\vimfiles"
