mklink %HOMEPATH%"\.vimrc" %HOMEPATH%"\dotfiles\.vimrc"
mklink %HOMEPATH%"\.gvimrc" %HOMEPATH%"\dotfiles\.gvimrc"
mklink %HOMEPATH%"\.dein.toml" %HOMEPATH%"\dotfiles\.dein.toml"
mklink %HOMEPATH%"\.gitconfig" %HOMEPATH%"\dotfiles\.gitconfig"
mklink %HOMEPATH%"\.gdbinit" %HOMEPATH%"\dotfiles\.gdbinit"
mklink %HOMEPATH%"\.screenrc" %HOMEPATH%"\dotfiles\.screenrc"
mklink %HOMEPATH%"\.minttyrc" %HOMEPATH%"\dotfiles\.minttyrc"
mklink %HOMEPATH%"\.bashrc.additional" %HOMEPATH%"\dotfiles\.bashrc.additional"
mklink /d %HOMEPATH%"\vimfiles" %HOMEPATH%"\dotfiles\vimfiles"
